
version: '3.8'

services:

  db:
    image: mariadb:latest 
    restart: always
    hostname: mariadb-host
    environment:
      MARIADB_ROOT_PASSWORD: Pass@123
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "Pass123!"
    ports:
      - '3306:3306'
    volumes: 
      - "./mariadb/data:/var/lib/mysql/data/"
      - "./mariadb/logs:/var/lib/mysql/logs/"
      - "./createguitar.sql:/docker-entrypoint-initdb.d/createguitar.sql"
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    links:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
    networks:
      - db-network

networks:
  db-network:
      name: db-network	
      driver: bridge
